services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lord_agency_frontend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
